baseURL = ""
languageCode = "en-us"
title = "Hugo Grayscale Theme"
theme = "grayscale"
disableKinds = [ "taxonomy", "taxonomyTerm" ]
themesDir = "themes"
publishDir = "public"

[params]
description = "A port of the Grayscale theme to Hugo"

[Author]
name = "RunningStream"
email = "dco@runningstream.net"

[Social]
twitter = "stream_running"
